service: MulMeokNyang
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    RDS_HOST: ${.env:RDS_HOST}
    RDS_USER: ${.env:RDS_USER}
    RDS_DATABASE: ${.env:RDS_DATABASE}
    RDS_PASSWORD: ${.env:RDS_PASSWORD}
  memorySize: 2048
  timeout: 15
  stage: prod
  region: ap-northeast-2

functions:
  findEmail:
    handler: findEmail.findEmail
    events:
      - http: 
          path: /getUserEmail
          method: get