service: MulMeokNyang
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    RDS_HOST: ${.env:RDS_HOST}
    RDS_USER: ${.env:RDS_USER}
    RDS_DATABASE: ${.env:RDS_DATABASE}
    RDS_PASSWORD: ${.env:RDS_PASSWORD}
    S3_BUCKET_NAME: ${.env:S3_BUCKET_NAME}
  memorySize: 2048
  timeout: 15
  stage: prod
  region: ap-northeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::mulmeoknyang-image/*
       

functions:
  findEmail:
    handler: findEmail.findEmail
    events:
      - http: 
          path: /getUserEmail
          method: get

  registUserProfile:
    handler: registUserProfile.registUserProfile
    events:
      - http:
          path: /registUserProfile
          method: post
  
  getCatMainInfo:
    handler: getCatMainInfo.getCatMainInfo
    events:
      - http:
          path: /getCatMainInfo
          method: get


